export const MedicalCenterSpecialitiesData = [
  {
    mainSpeciality: { ar: 'جلدية', en: 'Dermatology' },
    subSpeciality: [
      { ar: 'الأمراض الجلدية التناسلية', en: 'Genital Dermatology' },
      { ar: 'أمراض الأطفال الجلدية', en: 'Pediatric Dermatology' },
      { ar: 'الليزر و الجلدية التجميلية', en: 'Cosmetic Dermatology & Laser' },
      { ar: 'جلدية كبار', en: 'Adult Dermatology' },
      { ar: 'الذكورة', en: 'Andrology' },
      { ar: 'الحروق الجلدية', en: 'Burn Dermatolgy' },
      { ar: 'جلدية وتجميل عيون', en: 'Eyes Cosmetic Dermatology' },
      { ar: 'تجميل الوجه الجلدية', en: 'Facial Plastic Dermatology' },
      { ar: 'طب الأمراض التناسلية', en: 'Venerology' },
      { ar: 'امراض اليد الجلدية', en: 'Hand Dermatolgy' },
      { ar: 'الأمراض الجلدية تجميل الأنف', en: 'RhinoPlastic Dermatology' },
      { ar: 'طب باثولوجى الأمراض الجلدية', en: 'Dermatopathology' },
      { ar: 'الأمراض الجلدية الإجرائية', en: 'Procedural Dermatology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'اسنان', en: 'Dentistry' },
    subSpeciality: [
      { ar: 'طب أسنان بالغين', en: 'Adult Dentistry' },
      { ar: 'طب اسنان الاطفال', en: 'Pediatric Dentistry' },
      { ar: 'طب أسنان كبار السن', en: 'Elder Dentistry' },
      { ar: 'أمراض اللثة', en: 'Periodontics' },
      { ar: 'علاج جذور الاسنان', en: 'Endodontics' },
      { ar: 'التركيبات', en: 'Prosthodontics' },
      { ar: 'تقويم الأسنان', en: 'Orthodontics' },
      { ar: 'جراحة الفم والوجه والفكين', en: 'Oral & Maxillofacial Surgery' },
      { ar: 'طب الأسنان التجميلي', en: 'Cosmetic Dentistry' },
      { ar: 'زراعة الأسنان', en: 'Implantology' },
      { ar: 'طب الأسنان بالراديو الشفوي', en: 'oral Radio dentistry' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'نفسي - امراض السلوك', en: 'Psychiatry' },
    subSpeciality: [
      { ar: 'الطب النفسي للإدمان', en: 'AAddiction psychiatry' },
      { ar: 'الإرشاد الأسري', en: 'Family Counseling' },
      { ar: 'الطب النفسي والعصبي بالغين', en: 'Adult Neurology and Psychiatry' },
      { ar: 'الطب النفسي للمراهقين', en: 'Adolescent Psychiatry' },
      { ar: 'طب نفس الأطفال', en: 'Pediatric Psychiatry' },
      { ar: 'طب أعصاب الأطفال', en: 'Pediatric Neurology' },
      { ar: 'علم السموم', en: 'Toxicology' },
      { ar: 'طب أعصاب بالغين', en: 'Adult Neurology' },
      { ar: 'طب النفسية و الأعصاب', en: 'Neuropsychology' },
      { ar: 'الطب النفسي الدوائى', en: 'Psychopharmacology' },
      { ar: 'طب النوم واضطرابات الجهاز العصبى', en: 'Sleep Disorders and Somnology' },
      { ar: 'الطب النفسي الإداري', en: 'Administrative psychiatry' },
      { ar: 'الطب النفسي المجتمعي', en: 'Community psychiatry' },
      { ar: 'الطب النفسي للشيخوخة', en: 'Geriatric psychiatry' },
      { ar: 'الطب النفسي للإعاقات والتخلف الذهنى', en: 'Mental retardation psychiatry' },
      { ar: 'الطب النفسي للشيخوخة', en: 'Geriatric psychiatry' },
      { ar: 'الطب النفسي الجسدي', en: 'Psychosomatic medicine' },
      { ar: 'الطب النفسي للإرتباط والاستشارات والتواصل', en: 'Consultation and liaison psychiatry' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'اطفال وحديثي الولادة', en: 'General Pediatrics' },
    subSpeciality: [
      { ar: 'طب حديثي الولادة', en: 'New Born' },
      { ar: 'حساسية ومناعة الأطفال', en: 'Pediatric Allergy and Immunology' },
      { ar: 'طب الأطفال', en: 'Pediatrics' },
      { ar: 'كبد الأطفال', en: 'Pediatric Hepatology' },
      { ar: 'جراحة المسالك البولية للأطفال', en: 'Pediatric Urology' },
      { ar: 'روماتيزم الأطفال', en: 'Pediatric Rheumatology' },
      { ar: 'جهاز هضمي ومناظير اطفال', en: 'Pediatric Gastroenterology and Endoscopy' },
      { ar: 'الرضاعة الطبيعية', en: 'Natural Breast Feeding' },
      { ar: 'تخسيس وتغذية أطفال', en: 'Pediatric Dietitian and Nutrition' },
      { ar: 'طب النمو والسلوك أطفال', en: 'Developmental and behavioral pediatrics' },
      { ar: 'طب الأطفال إساءة معاملة الأطفال', en: 'child abuse pediatrics' },
      { ar: 'طب حديثي الولادة , الفترة المحيطة بالولادة', en: 'Neonatal and perinatal medicine' },
      { ar: 'أمراض قلب الأطفال', en: 'Pediatric cardiology' },
      { ar: 'طب الغدد الصماء أطفال', en: 'Pediatric endocrinology' },
      { ar: 'طب أمراض الرئة أطفال', en: 'Pediatric pulmonology' },
      { ar: 'طب روماتيزم الأطفال', en: 'Pediatric rheumatology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'نفسيه وعصبيه', en: 'Neurology' },
    subSpeciality: [
      { ar: 'الطب النفسي والعصبي بالغين', en: 'Adult Neurology and Psychiatry' },
      { ar: 'أمراض أعصاب بالغين', en: 'Adult Neurology' },
      { ar: 'طب اصابات الدماخ', en: 'Brain Injury Medicine' },
      { ar: 'طب أمراض الأعصاب الأطفال', en: 'Pediatric Neurology' },
      { ar: 'طب الفسيولوجية العصبية السريرية', en: 'Clinical Neurophysiology' },
      { ar: 'جراحة الأوعية الدموية العصبية التداخلية', en: 'Endovascular surgical neuroradiology' },
      { ar: 'طب إعاقات النمو العصبي', en: 'Neurodevelopmental disabilities' },
      { ar: 'طب الأعصاب الوعائية', en: 'Vascular neurology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة العظام', en: 'Orthopedic Surgery' },
    subSpeciality: [
      { ar: 'تشوهات العظام', en: 'Bone Deformities' },
      { ar: 'جراحات عظام القدم والكاحل', en: 'Foot and Ankle Orthopedics' },
      { ar: 'جراحات المفاصل التعويضية', en: 'Joint Replacement' },
      { ar: 'جراحة عظام بالغين', en: 'Adult Orthopedics' },
      { ar: 'الطب التقويمي', en: 'Osteopathic Medicine' },
      { ar: 'جراحة اليد والطرف العلوي', en: 'Hand and Upper Limb Surgery' },
      { ar: 'جراحة عظام بالغين', en: 'Adult Orthopedic Surgery' },
      { ar: 'جراحة عظام الاطفال', en: 'Pediatric Orthopedic Surgery' },
      { ar: 'اصابات ملاعب وتنظير مفاصل', en: 'Arthroscopy and Sports injuries' },
      { ar: 'الجراحة الميكروسكوبية', en: 'Microscopic Surgery' },
      { ar: 'روماتيزم بالغين', en: 'Adult Rheumatology' },
      { ar: 'جراحة العمود الفقري للبالغين', en: 'Adult Spine Surgery' },
      { ar: 'جراحة عظام الأطفال', en: 'Pediatric Orthopedics' },
      { ar: 'جراحات العظام الترميمية', en: 'reconstructive orthopaedics' },
      { ar: 'أورام الجهاز العضلي الهيكلي', en: 'Musculoskeletal oncology' },
      { ar: 'طب العظام الرياضي', en: 'Orthopaedic sports medicine' },
      { ar: 'جراحات اصابات العظام والحوادث', en: 'Orthopaedic trauma surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'نساء وتوليد و أمراض العقم', en: 'Obstetrics and Gynecology' },
    subSpeciality: [
      { ar: 'أمراض النساء', en: 'Gynaecology' },
      { ar: 'اطفال انابيب', en: 'IVF' },
      { ar: 'جراحة الأورام النسائية', en: 'Gynaecologic Oncological Surgery' },
      { ar: 'جراحة التجميل النسائية', en: 'Gynaecological Cosmetic Surgery' },
      { ar: 'طب الحوض الأنثوي والجراحة الترميمية', en: 'Female pelvic medicine and reconstructive surgery' },
      { ar: 'جراحة الأورام النسائية', en: 'Gynecologic oncology surgery' },
      { ar: 'طب الأم والجنين', en: 'Maternal-fetal medicine' },
      { ar: 'طب الغدد الصماء التناسلية والعقم', en: 'Reproductive endocrinoloy and infertility' },
      { ar: 'التوليد', en: 'Obstetrics' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة انف واذن وحنجرة', en: 'Ear, Nose and Throat' },
    subSpeciality: [
      { ar: 'جراحة انف واذن وحنجرة كبار', en: 'Adult Ear, Nose and throat Surgery' },
      { ar: 'جراحة انف واذن وحنجرة اطفال', en: 'Pediatric Ear, Nose and throat Surgery' },
      { ar: 'اضطرابات السمع والتوازن', en: 'Hearing and Balance Disorder' },
      { ar: 'سمعيات الكبار', en: 'Adult Audiology' },
      { ar: 'سمعيات الأطفال', en: 'Pediatric Audiology' },
      { ar: 'طب أعصاب الأذن', en: 'Otology neurotology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض القلب والأوعية دموية', en: 'CardioVascular Medicine' },
    subSpeciality: [
      { ar: 'أمراض قلب الأطفال', en: 'Pediatric Cardiology' },
      { ar: 'أمراض القلب للبالغين', en: 'Adult Cardiology' },
      { ar: 'أمراض الأوعية الدموية عند البالغين', en: 'Adult Vascular Diseases' },
      { ar: 'أمراض الأوعية الدموية لدى الأطفال', en: 'Pediatric Vascular Diseases' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'امراض دم', en: 'Hematology' },
    subSpeciality: [
      { ar: 'أمراض دم بالغين', en: 'Adult Hematology' },
      { ar: 'أمراض دم الأطفال', en: 'Pediatric Hematology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'باطنة أمراض السكرى', en: 'Diabetology' },
    subSpeciality: [
      { ar: 'سكري وغدد صماء كبار', en: 'Adult Diabetes and Endocrinology' },
      { ar: 'سكري وغدد صماء اطفال', en: 'Pediatric Diabetes and Endocrinology' },
      { ar: 'علاج أمراض القدم السكري', en: 'Diabetic Foot treatment' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'باطنة أمراض الغدد الصماء', en: 'Endocrinology' },
    subSpeciality: [
      { ar: 'أمراض غدد صماء كبار', en: 'Adult Endocrinology' },
      { ar: 'أمراض غدد صماء اطفال', en: 'Pediatric Endocrinology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'باطنة اورام', en: 'Oncology' },
    subSpeciality: [
      { ar: 'أورام الكبار', en: 'Adult Oncology' },
      { ar: 'علاج الأورام بالإشعاع', en: 'Radiation Oncology' },
      { ar: 'أورام الأطفال', en: 'Pediatric Oncology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'تخسيس وتغذية', en: 'Dietitian and Nutrition' },
    subSpeciality: [
      { ar: 'تخسيس وتغذية بالغين', en: 'Adult Dietitian and Nutrition' },
      { ar: 'تخسيس وتغذية اطفال', en: 'Pediatric Dietitian and Nutrition' },
      { ar: 'أمراض سوء التغذية', en: 'Malnutrition and Nutritional Disorders' },
      { ar: 'أمراض السمنة', en: 'Obesity Disorders' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة اطفال', en: 'Pediatric Surgery' },
    subSpeciality: [
      { ar: 'جراحة الأطفال العامة', en: 'Pediatric General Surgery' },
      { ar: 'جراحة المسالك البولية للأطفال', en: 'Pediatric Urology Surgery' },
      { ar: 'جراحة صدر الأطفال', en: 'Pediatric Thoracic Surgery' },
      { ar: 'جراحة الجهاز الهضمي للأطفال', en: 'Pediatric Gastroenterological Surgery' },
      { ar: 'جراحة تشوهات الأطفال والعيوب الخلقية', en: 'Pediatric Deformities and Birth Defects Surgery' },
      { ar: 'جراحة اورام الاطفال', en: 'Pediatric Oncology Surgery' },
      { ar: 'جراحة المسالك البولية للأطفال', en: 'Pediatric Urology Surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض باطنية', en: 'Internal Medicine' },
    subSpeciality: [
      { ar: 'سكري وغدد صماء كبار', en: 'Adult Diabetes and Endocrinology' },
      { ar: 'كلى كبار', en: 'Adult Nephrology' },
      { ar: 'جهاز هضمي ومناظير كبار', en: 'Adult Gastroenterology and Endoscopy' },
      { ar: 'طب القلب التداخلى والقسطرة', en: 'Interventional Cardiology' },
      { ar: 'طب الفسيولوجيا الكهربية والقلب السريرى ', en: 'Clinical cardiac electrophysiology' },
      { ar: 'طب الأمراض الصدرية وأجهزة التنفس', en: 'Pulmonary Disease and Respirator' },
      { ar: 'أمراض معدية', en: 'Infectious Diseases' },
      { ar: 'كبد بالغين', en: 'Adult Hepatology' },
      { ar: 'أمراض القلب للبالغين', en: 'Adult Cardiology' },
      { ar: 'تخسيس وتغذية بالغين', en: 'Adult Dietitian and Nutrition' },
      { ar: 'طب الغدد الصماء والسكرى والأيض الغذائى', en: 'Endocrinology, diabetes, and metabolism' },
      { ar: 'كبد الأطفال', en: 'Pediatric Hepatology' },
      { ar: 'جراحة المسالك البولية للبالغين', en: 'Adult Urology' },
      { ar: 'صدر وجهاز تنفسي بالغين', en: 'Adult Chest and Respiratory' },
      { ar: 'روماتيزم كبار', en: 'Adult Rheumatology' },
      { ar: 'أمراض الدم بالغين', en: 'Adult Hematology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة أورام', en: 'Oncology Surgery' },
    subSpeciality: [
      { ar: 'جراحة الأورام النسائية', en: 'Gynaecologic Oncological Surgery' },
      { ar: 'جراحة اورام كبار', en: 'Adult Oncology Surgery' },
      { ar: 'جراحات أورام الثدي', en: 'Breast Tumor Surgery' },
      { ar: 'جراحات أورام القولون', en: 'Colon Tumor Surgery' },
      { ar: 'جراحات أورام الكبد', en: 'Liver Tumor Surgery' },
      { ar: 'جراحات أورام الجهاز الهضمى', en: 'GIT Tumor Surgery' },
      { ar: 'جراحة اورام الاطفال', en: 'Pediatric Oncology Surgery' },
      { ar: 'جراحات أورام البروستاتا', en: 'Prostate Tumor Surgery' },
      { ar: 'جراحات أورام الرئة', en: 'Lung Tumor Surgery' },
      { ar: 'جراحات أورام العظام', en: 'Orthopedic Tumor Surgery' },
      { ar: 'جراحات أورام المخ', en: 'Brain Tumor Surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة اوعية دموية', en: 'Vascular Surgery' },
    subSpeciality: [
      { ar: 'علاج أمراض القدم السكري', en: 'Diabetic Foot treatment' },
      { ar: 'جراحة الأوعية الدموية للأطفال', en: 'Pediatric Vascular Surgery' },
      { ar: 'جراحة اوعية دموية كبار', en: 'Adult Vascular Surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة تجميل', en: 'Plastic Surgery' },
    subSpeciality: [
      { ar: 'جراحة الأطفال العامة', en: 'Pediatric General Surgery' },
      { ar: 'جراحة المسالك البولية للأطفال', en: 'Pediatric Urology Surgery' },
      { ar: 'جراحة صدر الأطفال', en: 'Pediatric Thoracic Surgery' },
      { ar: 'جراحات أورام الثدي', en: 'Breast Tumor Surgery' },
      { ar: 'جراحات تجميل الثدي', en: 'Breast aesthetic surgery' },
      { ar: 'جراحة القحف الوجهي والوجه', en: 'Craniofacial surgery' },
      { ar: 'جراحات اليد', en: 'Hand surgery' },
      { ar: 'جراحات التجميل الميكروسكوبية والدقيقة', en: 'Microscopic Plastic surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحات الجهاز الهضمى والمناظير', en: 'GIT and Laparoscopic Surgery' },
    subSpeciality: [
      { ar: 'جراحة السمنة', en: 'Bariatric and Obesity Surgery' },
      { ar: 'جراحة الجهاز الهضمي للبالغين', en: 'Adult Gastroenterological Surgery' },
      { ar: 'جراحة اورام كبار', en: 'Adult GIT Oncology Surgery' },
      { ar: 'جراحات البطن والجهاز الهضمى', en: 'Abdominal and GIT Surgery' },
      { ar: 'جراحة الغدد الصماء', en: 'Endocrinal Surgery' },
      { ar: 'جراحات المنظار الجراحى والجراحات المحدودة', en: 'Laparoscopic & Minimal invasive surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة عامة', en: 'General Surgery' },
    subSpeciality: [
      { ar: 'جراحة الأطفال العامة', en: 'Pediatric General Surgery' },
      { ar: 'عملية جراحية في البطن', en: 'Abdominal Surgery' },
      { ar: 'جراحة الغدد الصماء', en: 'Endocrinal Surgery' },
      { ar: 'جراحة الجهاز الهضمي للبالغين', en: 'Adult Gastroenterological Surgery' },
      { ar: 'جراحة اورام كبار', en: 'Adult Oncology Surgery' },
      { ar: 'جراحة عامة كبار', en: 'Adult General Surgery' },
      { ar: 'جراحة الجهاز الهضمي للأطفال', en: 'Pediatric Gastroenterological Surgery' },
      { ar: 'جراحة تشوهات الأطفال والعيوب الخلقية', en: 'Pediatric Deformities and Birth Defects Surgery' },
      { ar: 'جراحات الرضوض والحوادث', en: 'Trauma Surgery' },
      { ar: 'جراحة الأورام النسائية', en: 'Gynaecologic OncoSurgery' },
      { ar: 'جراحات الفم والوجه والفكين', en: 'Oral & Maxillofacial Surgery' },
      { ar: 'جراحات الشرج والقولون', en: 'Colon and rectal surgery' },
      { ar: 'الرعاية الحرجة الجراحية', en: 'Surgical critical care' },
      { ar: 'جراحة الفم والوجه والفكين', en: 'Oral & Maxillofacial Surgery' },
      { ar: 'جراحة الفم والوجه والفكين', en: 'Oral & Maxillofacial Surgery' },
      { ar: 'جراحة الفم والوجه والفكين', en: 'Oral & Maxillofacial Surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة عمود فقري', en: 'Spine Surgery' },
    subSpeciality: [
      { ar: 'جراحة العمود الفقري للبالغين', en: 'Adult Spine Surgery' },
      { ar: 'تشوهات العظام', en: 'Bone Deformities' },
      { ar: 'جراحة استبدال المفاصل', en: 'Joint Replacement' },
      { ar: 'جراحة عظام كبار', en: 'Adult Orthopedic Surgery' },
      { ar: 'جراحة العمود الفقري للأطفال', en: 'Pediatric Spine Surgery' },
      { ar: 'الجراحة الميكروسكوبية', en: 'Microscopic Surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة قلب وصدر', en: 'CardioThoracic Surgery' },
    subSpeciality: [
      { ar: 'جراحة قلب الأطفال', en: 'Pediatric CardioThoracic Surgery' },
      { ar: 'جراحات القلب الخلقية', en: 'Congenital cardiac surgery' },
      { ar: 'جراحةالقلب للبالغين', en: 'Adult CardioThoracic Surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة مخ واعصاب', en: 'Neurosurgery' },
    subSpeciality: [
      { ar: ' جراحة مخ و أعصاب كبار', en: 'Adult Neurosurgery' },
      { ar: 'جراحة مخ و أعصاب أطفال', en: 'Pediatric Neurosurgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جهاز هضمي ومناظير', en: 'Gastroenterology and Endoscopy' },
    subSpeciality: [
      { ar: 'أمراض كبد بالغين', en: 'Adult Hepatology' },
      { ar: 'جهاز هضمي ومناظير كبار', en: 'Adult Gastroenterology and Endoscopy' },
      { ar: 'الطب الباطني للبالغين', en: 'Adult Internal Medicine' },
      { ar: 'كبد الأطفال', en: 'Pediatric Hepatology' },
      { ar: 'جهاز هضمي ومناظير اطفال', en: 'Pediatric Gastroenterology and Endoscopy' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض الحساسية والمناعة', en: 'Allergy and Immunology' },
    subSpeciality: [
      { ar: 'أمراض حساسية ومناعة كبار', en: 'Adult Allergy and Immunology' },
      { ar: 'أمراض حساسية المناعة الذاتية', en: 'Autoimmune Allergy' },
      { ar: 'أمراض حساسية العيون', en: 'Ophthalmologic Allergy' },
      { ar: 'أمراض حساسية ومناعة الأطفال', en: 'Pediatric Allergy and Immunology' },
      { ar: 'أمراض حساسية الجلد', en: 'Skin Allergy' },
      { ar: 'أمراض صدر وجهاز تنفسي بالغين', en: 'Adult Chest and Respiratory' },
      { ar: 'أمراض صدر وجهاز تنفسي اطفال', en: 'Pediatric Chest and Respiratory' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'حقن مجهري واطفال انابيب', en: 'IVF and Infertility' },
    subSpeciality: [
      { ar: 'أمراض النساء', en: 'Gynaecology' },
      { ar: 'اطفال انابيب', en: 'IVF' },
      { ar: 'جراحة الأورام النسائية', en: 'Gynaecologic Oncological Surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'ذكورة وعقم', en: 'Andrology and Male Infertility' },
    subSpeciality: [
      { ar: ' أمراض الذكورة', en: 'Andrology' },
      { ar: 'أمراض عقم الرجال', en: 'Male Infertility' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض الروماتيزم', en: 'Rheumatology' },
    subSpeciality: [
      { ar: 'روماتيزم كبار', en: 'Adult Rheumatology' },
      { ar: 'روماتيزم الأطفال', en: 'Pediatric Rheumatology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'سمعيات', en: 'Audiology' },
    subSpeciality: [
      { ar: 'اضطرابات السمع والتوازن', en: 'Hearing and Balance Disorder' },
      { ar: 'سمعيات الكبار', en: 'Adult Audiolog' },
      { ar: 'سمعيات الأطفال', en: 'Pediatric Audiology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض الصدر والجهاز تنفسي', en: 'Chest and Respiratory Medicine' },
    subSpeciality: [
      { ar: 'صدر وجهاز تنفسي بالغين', en: 'Adult Chest and Respiratory' },
      { ar: 'صدر وجهاز تنفسي اطفال', en: 'Pediatric Chest and Respiratory' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب الأسرة', en: 'Family Medicine' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب المسنين', en: 'Geriatric Medicine' },
    subSpeciality: [
      { ar: 'أمراض الشيخوخة و كبار السن', en: 'Senility & Geriatric Disorders' },
      { ar: 'طب حركات كبار السن', en: 'Elder Mobility Disorders' },
      { ar: 'أمراض سوء التغذية مسنين', en: 'Elder Nutrition Disorders' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب تقويمي', en: 'Osteopathy Medicine' },
    subSpeciality: [
      { ar: 'العلاج الطبيعي للبالغين', en: 'Adult Physiotherapy' },
      { ar: 'الاصابات الرياضية', en: 'Sport Injuries' },
      { ar: 'إعادة تأهيل', en: 'Rehabilitation' },
      { ar: 'تخسيس وتغذية بالغين', en: 'Adult Dietitian and Nutrition' },
      { ar: 'تخسيس وتغذية اطفال', en: 'Pediatric Dietitian and Nutrition' },
      { ar: 'العلاج الطبيعي للأطفال', en: 'Pediatric Physiotherapy' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'علاج الآلام', en: 'Pain Management' },
    subSpeciality: [
      { ar: 'علاج آلام البالغين', en: 'Adult Pain Management' },
      { ar: 'علاج آلام الأطفال', en: 'Pediatric Pain Management' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'علاج طبيعي واصابات ملاعب', en: 'Physiotherapy and Sport Injuries' },
    subSpeciality: [
      { ar: 'العلاج الطبيعي للبالغين', en: 'Adult Physiotherapy' },
      { ar: 'الاصابات الرياضية', en: 'Sport Injuries' },
      { ar: 'إعادة تأهيل', en: 'Rehabilitation' },
      { ar: 'العلاج الطبيعي للأطفال', en: 'Pediatric Physiotherapy' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب أمراض العيون (رمد)', en: 'Ophthalmology' },
    subSpeciality: [
      { ar: 'طب عيون كبار', en: 'Adult Ophthalmology' },
      { ar: 'طب ارتفاع ضغط العين والمياه الزرقاء', en: 'Glaucoma ophthalmology' },
      { ar: 'تصحيح الإبصار وإعتام عدسة العين', en: 'Vision Correction and Cataract' },
      { ar: 'طب عيون الأطفال', en: 'Pediatric Ophthalmology' },
      { ar: 'طب أعصاب العيون', en: 'Neuro-ophthalmology' },
      { ar: 'جراحة الشبكية والجسم الزجاجي', en: 'Vitreous Body and Retinal Surgery' },
      { ar: 'إعادة التأهيل البصري', en: 'Visual Rehabilitation' },
      { ar: 'طب الجزء الأمامى من العين و القرنية', en: 'Anterior segment/cornea ophthalmology' },
      { ar: 'طب أورام العين', en: 'Ocular oncology' },
      { ar: 'جراحة العيون التجميلية والترميمية', en: 'Ophthalmic Plastic & Reconstructive Surgery' },
      { ar: 'طب الحول واختلال الإبصار', en: 'Strabismus ophthalmology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض الكبد', en: 'Hepatology' },
    subSpeciality: [
      { ar: 'كبد بالغين', en: 'Adult Hepatology' },
      { ar: 'كبد الأطفال', en: 'Pediatric Hepatology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض الكلى', en: 'Nephrology' },
    subSpeciality: [
      { ar: 'كلى كبار', en: 'Adult Nephrology' },
      { ar: 'طب كلى الأطفال', en: 'Pediatric Nephrology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الاشعه التشخيصية', en: 'Radiology' },
    subSpeciality: [
      { ar: 'الأشعة التشخيصية', en: 'Diagnostic Radiology' },
      { ar: 'الأشعة التداخلية و تدخلات الأوعية الدموية', en: 'Vascular and Interventional Radiology' },
      { ar: 'الأشعة النووية', en: 'Nuclear Radiology' },
      { ar: 'أشعة طب المخ والأعصاب', en: 'Neuroradiology' },
      { ar: 'أشعة علاج الأورام', en: 'Radiation Oncology' },
      { ar: 'أشعة', en: 'X Ray' },
      { ar: 'التصوير المقطعي بالموجات الفوق صوتية', en: 'Ultrasound' },
      { ar: 'تصوير مقطعي', en: 'CT' },
      { ar: 'ماسح التصوير المقطعي بالإصدار البوزيترون', en: 'PET CT' },
      { ar: 'رنين مغناطيسي', en: 'MRI' },
      { ar: 'تصوير الثدي', en: 'Breast Imaging' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'جراحة المسالك البولية', en: 'Urology Surgery' },
    subSpeciality: [
      { ar: 'أمراض كلى كبار', en: 'Adult Nephrology' },
      { ar: 'ذكورة', en: 'Andrology' },
      { ar: 'جراحة المسالك البولية للأطفال', en: 'Pediatric Urology Surgery' },
      { ar: 'طب المسالك العصبى', en: 'Neurourology' },
      { ar: 'جراحة المسالك البولية للبالغين', en: 'Adult Urology' },
      { ar: 'أورام المسالك البولية', en: 'Urologic oncology' },
      { ar: 'جراحة زراعة الكلى', en: 'Renal transplant surgery' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'معامل طبية و تحاليل', en: 'Laboratories' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'أمراض الطب العامة والجراحة', en: 'General Medicine and Surgery' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'نطق وتخاطب', en: 'Phoniatrics (Speech)' },
    subSpeciality: [
      { ar: 'تخاطب الكبار', en: 'Adult Phoniatrics' },
      { ar: 'تخاطب الأطفال', en: 'Pediatric Phoniatrics' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب التخدير', en: 'Anesthesia Medicine' },
    subSpeciality: [
      { ar: 'طب التخدير والعناية المركزية', en: 'Anaethesia and Intensive care' },
      { ar: 'طب تخدير الأطفال والعناية المركزة', en: 'Pediatric Anaethesia and Intensive Care' },
      { ar: 'طب العناية المركزة أطفال', en: 'Pediatric Intensive care' },
      { ar: 'طب التخدير أطفال و بالغين', en: 'Adult and Pediatric Anesthesia' },
      { ar: 'طب العناية المركزة الجراحية', en: 'Surgical Intensive Care' },
      { ar: 'طب رعاية حالات الإحتضار والرعاية التلطيفية', en: 'Hospice and Palliative care' },
      { ar: 'طب علاج الألم', en: 'Pain Medicine' },
      { ar: 'طب العنايةالحرجة', en: 'Critical Care Medicine' },
      { ar: 'طب علم واضطرابات النوم', en: 'Sleep Medicine' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب الرعاية الحرجة و المركزة', en: 'Critical and Intensive Care Medicine' },
    subSpeciality: [
      { ar: 'طب العناية الحرجة و المركزة أطفال', en: 'Pediatric Critical and Intensive Care' },
      { ar: 'طب العناية الحرجة و المركزة بالغين', en: 'Adult and Pediatric Critical and Intensive Care' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب الطوارئ', en: 'Emergency Medicine' },
    subSpeciality: [
      { ar: 'طب الطوارئ أطفال', en: 'Pediatric Emergency Medicine' },
      { ar: 'طب العنايةالحرجة', en: 'Critical Care Medicine' },
      { ar: 'طب الرياضات والملاعب', en: 'Sports Medicine' },
      { ar: 'علم السموم الطبية', en: 'Medical Toxicology' },
      { ar: 'طب الأعماق و علم الضغط المرتفع ', en: 'Undersea and Hyperbaric Medicine' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب الوبائيات', en: 'Epidemiology & Infectious Diseases' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب المناطق الحارة', en: 'Tropical Medicine' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الباثولوجيا', en: 'Pathology' },
    subSpeciality: [
      { ar: 'طب الباثولوجيا الإكلينيكية', en: 'Clinical Pathology' },
      { ar: 'طب تخزين الدم ونقل الدم', en: 'Blood banking and transfusion medicine' },
      { ar: 'علم الأمراض التشريحي', en: 'Anatomical pathology' },
      { ar: 'علم الأمراض الكيميائي', en: 'Chemical pathology' },
      { ar: 'علم الأمراض الخلوي', en: 'Cytopathology' },
      { ar: 'طب الأمراض الشرعى', en: 'Forensic pathology' },
      { ar: 'علم الأمراض الوراثي', en: 'Genetic pathology' },
      { ar: 'أمراض المناعة', en: 'Immunopathology' },
      { ar: 'علم الأحياء الدقيقة الطبية', en: 'Medical microbiology' },
      { ar: 'علم الأمراض الجزيئي', en: 'Molecular pathology' },
      { ar: 'علم الأمراض العصبية', en: 'Neuropathology' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب العاملين بالمؤسسة', en: 'Employee and Occupational Medicine' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الطب المنزلى', en: 'Home Healthcare' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الطب عن بعد والاستشارات الطبية', en: 'Telemedicine and Consultation' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب علم التشريح', en: 'Human Anatomy' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب علم الوظائف الحيوية للإنسان', en: 'Human Physiology' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الطب الشرعى', en: 'Forensic Medicine' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'طب علم الجينات و الوراثة', en: 'Medical Genetics' },
    subSpeciality: [
      { ar: 'طب علم الوراثة البيوكيميائية', en: 'Biochemical genetics' },
      { ar: 'طب علم الوراثة الخلوية الإكلينيكية', en: 'Clinical Cytogenetics' },
      { ar: 'علم الأمراض الوراثي الجزيئي', en: 'Molecular Genetic Pathology' },
      { ar: 'طب علم الوراثة الإكلينيكية', en: 'Clinical Genetics' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الطب النووى', en: 'NUCLEAR MEDICINE' },
    subSpeciality: [],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الطب الطبيعي وإعادة التأهيل', en: 'PHYSICAL MEDICINE AND REHABILITATION' },
    subSpeciality: [
      { ar: 'الطب العصبي العضلي', en: 'Neuromuscular medicine' },
      { ar: 'طب إعادة تأهيل الأطفال', en: 'Pediatric rehabilitation medicine' },
      { ar: 'طب إصابات الحبل الشوكي', en: 'Spinal cord injury medicine' },
      { ar: 'طب علاج الألم', en: 'Pain Medicine' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
  {
    mainSpeciality: { ar: 'الطب الوقائى', en: 'PREVENTIVE MEDICINE' },
    subSpeciality: [
      { ar: 'طب علوم الطيران', en: 'Aerospace medicine' },
      { ar: 'علم السموم الطبية', en: 'Medical toxicology' },
      { ar: 'الطب المهني', en: 'Occupational medicine' },
      { ar: 'طب الصحة العامة', en: 'Public health medicine' },
    ],
    businessType: { en: 'Medical Center', ar: 'مركز طبي' },
  },
];
