export const SubscriptionPackages = [
  {
    type: 'silver',
    userType: 'indiv',
    priceMonthly: 25,
    priceAnnualy: 0,
    messagesMonthly: '1000',
    inMailSMSMonthly: '10',
    storage: 10,
    sharing: 'Individuals',
    outboundPatientSharing: 'Basic 5 Pt. add: 1 Pt./1 registered invitee',
    viewSharedPatients: '10',
    pollFeatureMonthly: '',
    messageRetentionAndDeletion: 'Up to 2 Months then replaced by New Messages N.B. No Back Up',
    umedmiBotResponses: '',
    callVideoFeature: 'One-to-one',
    autoScheduler: 'Reservations SMS',
    ADSBlocker: '',
    templates: 'Basic templates',
    clinicSheetBuilder: '',
    dashboard: 'Basic',
    printing: 'Basic',
    voiceNotesAndUploads: '',
    voiceRecognition: '',
    handwritingRecognition: '',
    extractForms: '',
  },
  {
    type: 'gold',
    userType: 'indiv',
    priceMonthly: 150,
    priceAnnualy: 1500,
    messagesMonthly: '10000',
    inMailSMSMonthly: '50',
    storage: 30,
    sharing: '< 3 Groups',
    outboundPatientSharing: 'Up to 25 Pt. add: 5 Pt./1 registered invitee',
    viewSharedPatients: '25',
    pollFeatureMonthly: '5',
    messageRetentionAndDeletion: 'Up to 2 Months then Auto Back Up (New BU replaces the old)',
    umedmiBotResponses: 'Enabled UniDirectional English Only',
    callVideoFeature: 'Up to 3 individuals',
    autoScheduler: '+ Promotions/offers SMS',
    ADSBlocker: 'General ADS (targeted ADS allowed)',
    templates: 'Up to 50 templates',
    clinicSheetBuilder: 'Basic sheet building',
    dashboard: 'Detailed Fields (up to two sub levels)',
    printing: 'Single Subfields allowed',
    voiceNotesAndUploads: 'Voice Notes',
    voiceRecognition: 'English',
    handwritingRecognition: 'OCR (Regular HW)',
    extractForms: 'PDF',
  },
  {
    type: 'titanium',
    userType: 'indiv',
    priceMonthly: 300,
    priceAnnualy: 3000,
    messagesMonthly: '50000',
    inMailSMSMonthly: '100',
    storage: 50,
    sharing: 'institutions',
    outboundPatientSharing: 'Up to 50 Pt. add: 10 Pt./1 registered invitee',
    viewSharedPatients: '100',
    pollFeatureMonthly: '20',
    messageRetentionAndDeletion: 'Cumulative Back Ups every 2 Months',
    umedmiBotResponses: 'Enabled Bi-Directional user can send SMS to bot like Slack',
    callVideoFeature: 'Conference call',
    autoScheduler: '+Patient Survey Forms',
    ADSBlocker: 'Enabled',
    templates: 'Up to 100 templates',
    clinicSheetBuilder: 'Advanced sheet with Calc',
    dashboard: 'Full Dashboard + Graphics layouts',
    printing: 'Single Subfields & Custom printing (Dr logo)',
    voiceNotesAndUploads: 'Voice Notes & uploads (single / card)',
    voiceRecognition: 'English & Arabic',
    handwritingRecognition: 'Cursive HW',
    extractForms: 'PDF & image',
  },
  {
    type: 'platinium',
    userType: 'indiv',
    priceMonthly: 500,
    priceAnnualy: 5000,
    messagesMonthly: 'unlimited',
    inMailSMSMonthly: 'unlimited',
    storage: 100,
    sharing: 'unlimited',
    outboundPatientSharing: 'Unlimited',
    viewSharedPatients: 'Unlimited',
    pollFeatureMonthly: 'unlimited',
    messageRetentionAndDeletion: 'Cumulative Back Ups every 2 Months',
    umedmiBotResponses: 'Bi-Directional & Bi-Lingual',
    callVideoFeature: 'Conference audio video calls',
    autoScheduler: '+ Msc./PhD study candidates Forms',
    ADSBlocker: 'Enabled with ADS View manager',
    templates: 'unlimited',
    clinicSheetBuilder: 'Advanced sheet with Calc. & branching logic',
    dashboard: 'Full Dashboard & AI Insights',
    printing: 'Multiple subfields & Custom  Printings',
    voiceNotesAndUploads: 'Voice Notes & uploads (multiple attachments / card)',
    voiceRecognition: '4 languages Support (E+Ar+Fr+German',
    handwritingRecognition: 'Cursive HW',
    extractForms: 'PDF, Image & Excel',
  },
  {
    type: 'silver',
    userType: 'corp',
    priceMonthly: 50,
    priceAnnualy: 0,
    messagesMonthly: '1000',
    inMailSMSMonthly: '10',
    storage: 10,
    sharing: 'Individuals',
    outboundPatientSharing: 'Basic 5 Pt. add: 1 Pt./1 registered invitee',
    viewSharedPatients: '10',
    pollFeatureMonthly: '',
    messageRetentionAndDeletion: 'Up to 2 Months then replaced by New Messages N.B. No Back Up',
    umedmiBotResponses: '',
    callVideoFeature: 'One-to-one',
    autoScheduler: 'Reservations SMS',
    ADSBlocker: '',
    templates: 'Basic templates',
    clinicSheetBuilder: '',
    dashboard: 'Basic',
    printing: 'Basic',
    voiceNotesAndUploads: '',
    voiceRecognition: '',
    handwritingRecognition: '',
    extractForms: '',
  },
  {
    type: 'gold',
    userType: 'corp',
    priceMonthly: 300,
    priceAnnualy: 3000,
    messagesMonthly: '10000',
    inMailSMSMonthly: '50',
    storage: 30,
    sharing: '< 3 Groups',
    outboundPatientSharing: 'Up to 25 Pt. add: 5 Pt./1 registered invitee',
    viewSharedPatients: '25',
    pollFeatureMonthly: '5',
    messageRetentionAndDeletion: 'Up to 2 Months then Auto Back Up (New BU replaces the old)',
    umedmiBotResponses: 'Enabled UniDirectional English Only',
    callVideoFeature: 'Up to 3 individuals',
    autoScheduler: '+ Promotions/offers SMS',
    ADSBlocker: 'General ADS (targeted ADS allowed)',
    templates: 'Up to 50 templates',
    clinicSheetBuilder: 'Basic sheet building',
    dashboard: 'Detailed Fields (up to two sub levels)',
    printing: 'Single Subfields allowed',
    voiceNotesAndUploads: 'Voice Notes',
    voiceRecognition: 'English',
    handwritingRecognition: 'OCR (Regular HW)',
    extractForms: 'PDF',
  },
  {
    type: 'titanium',
    userType: 'corp',
    priceMonthly: 600,
    priceAnnualy: 6000,
    messagesMonthly: '50000',
    inMailSMSMonthly: '100',
    storage: 50,
    sharing: 'institutions',
    outboundPatientSharing: 'Up to 50 Pt. add: 10 Pt./1 registered invitee',
    viewSharedPatients: '100',
    pollFeatureMonthly: '20',
    messageRetentionAndDeletion: 'Cumulative Back Ups every 2 Months',
    umedmiBotResponses: 'Enabled Bi-Directional user can send SMS to bot like Slack',
    callVideoFeature: 'Conference call',
    autoScheduler: '+Patient Survey Forms',
    ADSBlocker: 'Enabled',
    templates: 'Up to 100 templates',
    clinicSheetBuilder: 'Advanced sheet with Calc',
    dashboard: 'Full Dashboard + Graphics layouts',
    printing: 'Single Subfields & Custom printing (Dr logo)',
    voiceNotesAndUploads: 'Voice Notes & uploads (single / card)',
    voiceRecognition: 'English & Arabic',
    handwritingRecognition: 'Cursive HW',
    extractForms: 'PDF & image',
  },
  {
    type: 'platinium',
    userType: 'corp',
    priceMonthly: 1000,
    priceAnnualy: 10000,
    messagesMonthly: 'unlimited',
    inMailSMSMonthly: 'unlimited',
    storage: 100,
    sharing: 'unlimited',
    outboundPatientSharing: 'Unlimited',
    viewSharedPatients: 'Unlimited',
    pollFeatureMonthly: 'unlimited',
    messageRetentionAndDeletion: 'Cumulative Back Ups every 2 Months',
    umedmiBotResponses: 'Bi-Directional & Bi-Lingual',
    callVideoFeature: 'Conference audio video calls',
    autoScheduler: '+ Msc./PhD study candidates Forms',
    ADSBlocker: 'Enabled with ADS View manager',
    templates: 'unlimited',
    clinicSheetBuilder: 'Advanced sheet with Calc. & branching logic',
    dashboard: 'Full Dashboard & AI Insights',
    printing: 'Multiple subfields & Custom  Printings',
    voiceNotesAndUploads: 'Voice Notes & uploads (multiple attachments / card)',
    voiceRecognition: '4 languages Support (E+Ar+Fr+German',
    handwritingRecognition: 'Cursive HW',
    extractForms: 'PDF, Image & Excel',
  },
];
